#!/bin/bash

cd /cromwell_root
tmpDir=$(mkdir -p "/cromwell_root/tmp.a89a9eaa" && echo "/cromwell_root/tmp.a89a9eaa")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell_root

)
outbf9a51e0="${tmpDir}/out.$$" errbf9a51e0="${tmpDir}/err.$$"
mkfifo "$outbf9a51e0" "$errbf9a51e0"
trap 'rm "$outbf9a51e0" "$errbf9a51e0"' EXIT
touch '/cromwell_root/stdout' '/cromwell_root/stderr'
tee '/cromwell_root/stdout' < "$outbf9a51e0" &
tee '/cromwell_root/stderr' < "$errbf9a51e0" >&2 &
(
cd /cromwell_root


set -x
set -e

echo "project_id = terra-cold-pecan-4945" > ~/.bigqueryrc

for TABLE_ID in $(seq 1 1); do
  PARTITION_STRING=""
  CLUSTERING_STRING=""
  if [ false == "true" ]; then
    # assume clustering as well
    let "PARTITION_START=(${TABLE_ID}-1)*4000+1"
    let "PARTITION_END=$PARTITION_START+4000"
    let "PARTITION_STEP=1"
    PARTITION_FIELD="sample_id"
    CLUSTERING_FIELD="location"
    PARTITION_STRING="--range_partitioning=$PARTITION_FIELD,$PARTITION_START,$PARTITION_END,$PARTITION_STEP"
    CLUSTERING_STRING="--clustering_fields=$CLUSTERING_FIELD"
  fi

  if [ false = "true" ]; then
    printf -v PADDED_TABLE_ID "%03d" ${TABLE_ID}
    TABLE="gvs_1.sample_load_status_${PADDED_TABLE_ID}"
  else
    TABLE="gvs_1.sample_load_status"
  fi

  # Check that the table has not been created yet
  set +e
  bq show --project_id terra-cold-pecan-4945 $TABLE > /dev/null
  BQ_SHOW_RC=$?
  set -e
  if [ $BQ_SHOW_RC -ne 0 ]; then
    echo "making table $TABLE"
    echo '[{"name": "sample_id","type": "INTEGER","mode": "REQUIRED"},{"name":"status","type":"STRING","mode":"REQUIRED"}, {"name":"event_timestamp","type":"TIMESTAMP","mode":"REQUIRED"}]' > schema.json
    bq mk ${PARTITION_STRING} ${CLUSTERING_STRING} --project_id=terra-cold-pecan-4945 $TABLE schema.json
  fi
done
)  > "$outbf9a51e0" 2> "$errbf9a51e0"
echo $? > /cromwell_root/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell_root
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell_root
sync


)
mv /cromwell_root/rc.tmp /cromwell_root/rc
