#!/bin/bash

cd /cromwell_root
tmpDir=$(mkdir -p "/cromwell_root/tmp.f2b61e09" && echo "/cromwell_root/tmp.f2b61e09")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell_root

)
outfad27d9f="${tmpDir}/out.$$" errfad27d9f="${tmpDir}/err.$$"
mkfifo "$outfad27d9f" "$errfad27d9f"
trap 'rm "$outfad27d9f" "$errfad27d9f"' EXIT
touch '/cromwell_root/stdout' '/cromwell_root/stderr'
tee '/cromwell_root/stdout' < "$outfad27d9f" &
tee '/cromwell_root/stderr' < "$errfad27d9f" >&2 &
(
cd /cromwell_root


set -e

split -a 5 -l 20000 /cromwell_root/workflows-bucket-terra-cold-pecan-4945/GvsJointVariantCalling_job_2024-01-25T222932826Z/GvsJointVariantCalling/cae072db-c91b-49ee-a0c7-dca2ee2bf0bd/call-GvsUnified/GvsUnified/2b77704a-e1a7-4ceb-9c57-8176f385c73f/call-GvsImportGenomes/GvsImportGenomes/fad27d9f-1823-445f-9fef-c00eb782d39f/call-CurateInputLists/output_vcf_list_file batched_vcfs.
split -a 5 -l 20000 /cromwell_root/workflows-bucket-terra-cold-pecan-4945/GvsJointVariantCalling_job_2024-01-25T222932826Z/GvsJointVariantCalling/cae072db-c91b-49ee-a0c7-dca2ee2bf0bd/call-GvsUnified/GvsUnified/2b77704a-e1a7-4ceb-9c57-8176f385c73f/call-GvsImportGenomes/GvsImportGenomes/fad27d9f-1823-445f-9fef-c00eb782d39f/call-CurateInputLists/output_vcf_index_list_file batched_vcf_indexes.
split -a 5 -l 20000 /cromwell_root/workflows-bucket-terra-cold-pecan-4945/GvsJointVariantCalling_job_2024-01-25T222932826Z/GvsJointVariantCalling/cae072db-c91b-49ee-a0c7-dca2ee2bf0bd/call-GvsUnified/GvsUnified/2b77704a-e1a7-4ceb-9c57-8176f385c73f/call-GvsImportGenomes/GvsImportGenomes/fad27d9f-1823-445f-9fef-c00eb782d39f/call-CurateInputLists/output_sample_name_list_file batched_sample_names.
)  > "$outfad27d9f" 2> "$errfad27d9f"
echo $? > /cromwell_root/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell_root
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell_root
sync
# make the directory which will keep the matching files
mkdir /cromwell_root/glob-b8bdf6009093d2a121c20271c60baf67

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell_root/glob-b8bdf6009093d2a121c20271c60baf67/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell_root/batched_vcfs.* /cromwell_root/glob-b8bdf6009093d2a121c20271c60baf67 2> /dev/null ) || ( ln /cromwell_root/batched_vcfs.* /cromwell_root/glob-b8bdf6009093d2a121c20271c60baf67 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell_root/glob-b8bdf6009093d2a121c20271c60baf67 | grep -v cromwell_glob_control_file > /cromwell_root/glob-b8bdf6009093d2a121c20271c60baf67.list

# make the directory which will keep the matching files
mkdir /cromwell_root/glob-f5a9cc0d00d792726d568e80c4e678e7

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell_root/glob-f5a9cc0d00d792726d568e80c4e678e7/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell_root/batched_sample_names.* /cromwell_root/glob-f5a9cc0d00d792726d568e80c4e678e7 2> /dev/null ) || ( ln /cromwell_root/batched_sample_names.* /cromwell_root/glob-f5a9cc0d00d792726d568e80c4e678e7 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell_root/glob-f5a9cc0d00d792726d568e80c4e678e7 | grep -v cromwell_glob_control_file > /cromwell_root/glob-f5a9cc0d00d792726d568e80c4e678e7.list

# make the directory which will keep the matching files
mkdir /cromwell_root/glob-c320cc4d7cda6f427b3fb653dd039d40

# create the glob control file that will allow for the globbing to succeed even if there is 0 match
echo "This file is used by Cromwell to allow for globs that would not match any file.
By its presence it works around the limitation of some backends that do not allow empty globs.
Regardless of the outcome of the glob, this file will not be part of the final list of globbed files." > /cromwell_root/glob-c320cc4d7cda6f427b3fb653dd039d40/cromwell_glob_control_file

# hardlink or symlink all the files into the glob directory
( ln -L /cromwell_root/batched_vcf_indexes.* /cromwell_root/glob-c320cc4d7cda6f427b3fb653dd039d40 2> /dev/null ) || ( ln /cromwell_root/batched_vcf_indexes.* /cromwell_root/glob-c320cc4d7cda6f427b3fb653dd039d40 )

# list all the files (except the control file) that match the glob into a file called glob-[md5 of glob].list
ls -1 /cromwell_root/glob-c320cc4d7cda6f427b3fb653dd039d40 | grep -v cromwell_glob_control_file > /cromwell_root/glob-c320cc4d7cda6f427b3fb653dd039d40.list


)
mv /cromwell_root/rc.tmp /cromwell_root/rc
